import { useState } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import {
  SparklesIcon,
  DocumentTextIcon,
  ArrowDownTrayIcon,
  XMarkIcon,
  ExclamationTriangleIcon,
  CheckCircleIcon,
  ArrowPathIcon,
  ChartBarIcon,
  BeakerIcon,
  CpuChipIcon,
  HeartIcon,
} from '@heroicons/react/24/outline'
import axios from 'axios'
import {
  BarChart,
  Bar,
  RadarChart,
  Radar,
  PolarGrid,
  PolarAngleAxis,
  PolarRadiusAxis,
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
  Cell,
  PieChart,
  Pie,
} from 'recharts'

const API_BASE = 'http://localhost:8001'

interface FusionReport {
  id: number
  patient_id: number
  generated_at: string
  fusion_scores: {
    cognitive: number
    biomarker: number
    imaging: number
    integrated: number
    confidence: string
  }
  cross_modal: {
    consistency_score: number
    correlations: {
      cognitive_biomarker: number
      cognitive_imaging: number
      biomarker_imaging: number
    }
    has_conflicts: boolean
  }
  disease_analysis: {
    alzheimer: {
      score: number
      confidence: number
    }
    parkinson: {
      score: number
      confidence: number
    }
  }
  interpretation: {
    overall: string
    primary_concern: string
    confidence: number
  }
  report: {
    executive_summary: string
    detailed_findings: string
    risk_assessment: string
    recommendations: string
    follow_up_plan: string
  }
  quality: {
    data_completeness: number
    has_outliers: boolean
  }
}

export default function DataFusionReportsPage() {
  const [patientId, setPatientId] = useState('')
  const [selectedReport, setSelectedReport] = useState<FusionReport | null>(null)
  const queryClient = useQueryClient()

  // Fetch patient reports
  const { data: reports, isLoading } = useQuery<FusionReport[]>({
    queryKey: ['fusion-reports', patientId],
    queryFn: async () => {
      if (!patientId) return []
      const response = await axios.get(`${API_BASE}/api/v1/data-fusion/patient/${patientId}`)
      return response.data
    },
    enabled: !!patientId,
  })

  // Generate new report mutation
  const generateReport = useMutation({
    mutationFn: async (patId: number) => {
      const response = await axios.post(`${API_BASE}/api/v1/data-fusion/generate`, {
        patient_id: patId,
      })
      return response.data
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['fusion-reports', patientId] })
    },
  })

  const getInterpretationColor = (interpretation: string) => {
    switch (interpretation) {
      case 'normal':
        return 'bg-green-900/20 text-green-300 border-green-700/30'
      case 'mild_concern':
        return 'bg-yellow-900/20 text-yellow-300 border-yellow-700/30'
      case 'moderate_concern':
        return 'bg-orange-900/20 text-orange-300 border-orange-700/30'
      case 'high_concern':
        return 'bg-red-900/20 text-red-300 border-red-700/30'
      case 'critical':
        return 'bg-red-900/40 text-red-200 border-red-600/50'
      default:
        return 'bg-slate-800/50 text-slate-300 border-slate-700'
    }
  }

  const getConfidenceColor = (confidence: string) => {
    switch (confidence) {
      case 'very_high':
        return 'text-green-400'
      case 'high':
        return 'text-blue-400'
      case 'moderate':
        return 'text-yellow-400'
      case 'low':
        return 'text-orange-400'
      case 'very_low':
        return 'text-red-400'
      default:
        return 'text-slate-400'
    }
  }

  const downloadReport = (report: FusionReport) => {
    const content = `
MULTI-MODAL DATA FUSION REPORT
NeuroPredict-AI System

Report ID: ${report.id}
Generated: ${new Date(report.generated_at).toLocaleString()}
Patient ID: ${report.patient_id}

${report.report.executive_summary}

DETAILED FINDINGS:
${report.report.detailed_findings}

RISK ASSESSMENT:
${report.report.risk_assessment}

RECOMMENDATIONS:
${report.report.recommendations}

FOLLOW-UP PLAN:
${report.report.follow_up_plan}

---
Generated by NeuroPredict-AI Advanced Data Fusion System
PATENT PENDING - Multi-Modal Integration Algorithm
    `

    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `fusion-report-${report.id}-patient-${report.patient_id}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-950 via-purple-950/20 to-slate-950 p-6">
      {/* Header */}
      <div className="mb-8">
        <div className="flex items-center gap-3 mb-3">
          <div className="p-3 bg-gradient-to-br from-purple-500 to-pink-500 rounded-xl">
            <SparklesIcon className="h-8 w-8 text-white" />
          </div>
          <div>
            <h1 className="text-3xl font-bold text-white bg-gradient-to-r from-purple-400 to-pink-400 bg-clip-text text-transparent">
              Advanced Data Fusion
            </h1>
            <p className="text-slate-400 text-sm mt-1">
              Multi-Modal Medical Data Integration & Interpretation
            </p>
          </div>
        </div>
        
        <div className="bg-purple-900/20 border border-purple-700/30 rounded-lg p-4 mt-4">
          <p className="text-slate-300 text-sm leading-relaxed">
            <span className="font-semibold text-purple-300">PATENT PENDING:</span> This system implements a 
            <span className="text-purple-400 font-medium"> Multi-Modal Data Fusion Algorithm</span> that integrates 
            cognitive assessments, biomarker profiles, and neuroimaging findings through 
            confidence-weighted correlation analysis with automated conflict resolution and natural language report generation.
          </p>
        </div>
      </div>

      {/* Input Section */}
      <div className="bg-slate-900/60 rounded-2xl border border-slate-800 p-6 mb-6">
        <label className="block text-sm font-semibold text-slate-300 mb-3">
          Enter Patient ID to View/Generate Fusion Reports
        </label>
        <div className="flex gap-3">
          <input
            type="number"
            value={patientId}
            onChange={(e) => setPatientId(e.target.value)}
            placeholder="Patient ID (e.g., 1)"
            className="flex-1 bg-slate-950/60 border border-slate-700 rounded-lg px-4 py-3 text-white placeholder-slate-500 focus:border-purple-500 focus:ring-2 focus:ring-purple-500/40 transition-all"
          />
          <button
            onClick={() => patientId && generateReport.mutate(parseInt(patientId))}
            disabled={!patientId || generateReport.isPending}
            className="px-6 py-3 bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-500 hover:to-pink-500 disabled:from-slate-700 disabled:to-slate-700 text-white font-semibold rounded-lg transition-all flex items-center gap-2 disabled:cursor-not-allowed"
          >
            <SparklesIcon className="h-5 w-5" />
            {generateReport.isPending ? 'Generating...' : 'Generate Fusion Report'}
          </button>
        </div>
      </div>

      {/* Loading State */}
      {isLoading && (
        <div className="flex items-center justify-center py-12">
          <ArrowPathIcon className="h-8 w-8 text-purple-400 animate-spin" />
          <span className="ml-3 text-slate-400">Loading reports...</span>
        </div>
      )}

      {/* No Data State */}
      {!isLoading && patientId && reports?.length === 0 && (
        <div className="bg-slate-900/40 rounded-2xl border border-slate-800 p-12 text-center">
          <DocumentTextIcon className="h-16 w-16 text-slate-600 mx-auto mb-4" />
          <h3 className="text-xl font-semibold text-slate-300 mb-2">No Reports Found</h3>
          <p className="text-slate-500 mb-6">
            No fusion reports exist for Patient ID {patientId}.
          </p>
          <button
            onClick={() => generateReport.mutate(parseInt(patientId))}
            className="px-6 py-3 bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-500 hover:to-pink-500 text-white font-semibold rounded-lg transition-all inline-flex items-center gap-2"
          >
            <SparklesIcon className="h-5 w-5" />
            Generate First Report
          </button>
        </div>
      )}

      {/* Reports Grid */}
      {reports && reports.length > 0 && (
        <div className="space-y-6">
          {/* Summary Cards */}
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            <div className="bg-gradient-to-br from-blue-900/40 to-blue-950/40 border border-blue-700/30 rounded-xl p-4">
              <div className="flex items-center gap-3 mb-2">
                <CpuChipIcon className="h-6 w-6 text-blue-400" />
                <span className="text-xs font-semibold text-blue-300 uppercase">Cognitive</span>
              </div>
              <div className="text-2xl font-bold text-white">
                {reports[0]?.fusion_scores.cognitive.toFixed(1)}
              </div>
              <div className="text-xs text-blue-300/70 mt-1">Latest Score</div>
            </div>

            <div className="bg-gradient-to-br from-emerald-900/40 to-emerald-950/40 border border-emerald-700/30 rounded-xl p-4">
              <div className="flex items-center gap-3 mb-2">
                <BeakerIcon className="h-6 w-6 text-emerald-400" />
                <span className="text-xs font-semibold text-emerald-300 uppercase">Biomarker</span>
              </div>
              <div className="text-2xl font-bold text-white">
                {reports[0]?.fusion_scores.biomarker.toFixed(1)}
              </div>
              <div className="text-xs text-emerald-300/70 mt-1">Latest Score</div>
            </div>

            <div className="bg-gradient-to-br from-purple-900/40 to-purple-950/40 border border-purple-700/30 rounded-xl p-4">
              <div className="flex items-center gap-3 mb-2">
                <HeartIcon className="h-6 w-6 text-purple-400" />
                <span className="text-xs font-semibold text-purple-300 uppercase">Imaging</span>
              </div>
              <div className="text-2xl font-bold text-white">
                {reports[0]?.fusion_scores.imaging.toFixed(1)}
              </div>
              <div className="text-xs text-purple-300/70 mt-1">Latest Score</div>
            </div>

            <div className="bg-gradient-to-br from-pink-900/40 to-pink-950/40 border border-pink-700/30 rounded-xl p-4">
              <div className="flex items-center gap-3 mb-2">
                <ChartBarIcon className="h-6 w-6 text-pink-400" />
                <span className="text-xs font-semibold text-pink-300 uppercase">Integrated</span>
              </div>
              <div className="text-2xl font-bold text-white">
                {reports[0]?.fusion_scores.integrated.toFixed(1)}
              </div>
              <div className="text-xs text-pink-300/70 mt-1">Fusion Score</div>
            </div>
          </div>

          {/* Visualization Section */}
          {reports[0] && (
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              {/* Modality Scores Chart */}
              <div className="bg-slate-900/60 rounded-2xl border border-slate-800 p-6">
                <h3 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
                  <ChartBarIcon className="h-5 w-5 text-purple-400" />
                  Modality Scores Breakdown
                </h3>
                <ResponsiveContainer width="100%" height={250}>
                  <BarChart
                    data={[
                      {
                        name: 'Cognitive',
                        score: reports[0].fusion_scores.cognitive,
                        fill: '#60a5fa',
                      },
                      {
                        name: 'Biomarker',
                        score: reports[0].fusion_scores.biomarker,
                        fill: '#34d399',
                      },
                      {
                        name: 'Imaging',
                        score: reports[0].fusion_scores.imaging,
                        fill: '#a78bfa',
                      },
                      {
                        name: 'Integrated',
                        score: reports[0].fusion_scores.integrated,
                        fill: '#f472b6',
                      },
                    ]}
                  >
                    <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" />
                    <XAxis dataKey="name" stroke="#94a3b8" tick={{ fontSize: 12 }} />
                    <YAxis stroke="#94a3b8" tick={{ fontSize: 12 }} domain={[0, 100]} />
                    <Tooltip
                      contentStyle={{
                        backgroundColor: '#0f172a',
                        border: '1px solid #1e293b',
                        borderRadius: '8px',
                      }}
                    />
                    <Bar dataKey="score" radius={[8, 8, 0, 0]}>
                      {[0, 1, 2, 3].map((index) => (
                        <Cell key={`cell-${index}`} />
                      ))}
                    </Bar>
                  </BarChart>
                </ResponsiveContainer>
              </div>

              {/* Cross-Modal Correlations */}
              <div className="bg-slate-900/60 rounded-2xl border border-slate-800 p-6">
                <h3 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
                  <SparklesIcon className="h-5 w-5 text-purple-400" />
                  Cross-Modal Correlations
                </h3>
                <ResponsiveContainer width="100%" height={250}>
                  <RadarChart
                    data={[
                      {
                        subject: 'Cognitive-Biomarker',
                        value: reports[0].cross_modal.correlations.cognitive_biomarker * 100,
                        fullMark: 100,
                      },
                      {
                        subject: 'Cognitive-Imaging',
                        value: reports[0].cross_modal.correlations.cognitive_imaging * 100,
                        fullMark: 100,
                      },
                      {
                        subject: 'Biomarker-Imaging',
                        value: reports[0].cross_modal.correlations.biomarker_imaging * 100,
                        fullMark: 100,
                      },
                    ]}
                  >
                    <PolarGrid stroke="#1e293b" />
                    <PolarAngleAxis dataKey="subject" stroke="#94a3b8" tick={{ fontSize: 11 }} />
                    <PolarRadiusAxis angle={90} domain={[0, 100]} stroke="#94a3b8" />
                    <Radar
                      name="Correlation"
                      dataKey="value"
                      stroke="#a78bfa"
                      fill="#a78bfa"
                      fillOpacity={0.6}
                    />
                    <Tooltip
                      contentStyle={{
                        backgroundColor: '#0f172a',
                        border: '1px solid #1e293b',
                        borderRadius: '8px',
                      }}
                    />
                  </RadarChart>
                </ResponsiveContainer>
              </div>

              {/* Disease Analysis */}
              <div className="bg-slate-900/60 rounded-2xl border border-slate-800 p-6">
                <h3 className="text-lg font-semibold text-white mb-4">Disease-Specific Analysis</h3>
                <div className="space-y-4">
                  <div>
                    <div className="flex justify-between items-center mb-2">
                      <span className="text-sm font-medium text-slate-300">Alzheimer's Risk</span>
                      <span className="text-lg font-bold text-amber-400">
                        {reports[0].disease_analysis.alzheimer.score.toFixed(1)}%
                      </span>
                    </div>
                    <div className="w-full bg-slate-800 rounded-full h-3">
                      <div
                        className="bg-gradient-to-r from-amber-500 to-orange-500 h-3 rounded-full transition-all"
                        style={{ width: `${reports[0].disease_analysis.alzheimer.score}%` }}
                      />
                    </div>
                    <div className="text-xs text-slate-500 mt-1">
                      Confidence: {(reports[0].disease_analysis.alzheimer.confidence * 100).toFixed(1)}%
                    </div>
                  </div>

                  <div>
                    <div className="flex justify-between items-center mb-2">
                      <span className="text-sm font-medium text-slate-300">Parkinson's Risk</span>
                      <span className="text-lg font-bold text-purple-400">
                        {reports[0].disease_analysis.parkinson.score.toFixed(1)}%
                      </span>
                    </div>
                    <div className="w-full bg-slate-800 rounded-full h-3">
                      <div
                        className="bg-gradient-to-r from-purple-500 to-pink-500 h-3 rounded-full transition-all"
                        style={{ width: `${reports[0].disease_analysis.parkinson.score}%` }}
                      />
                    </div>
                    <div className="text-xs text-slate-500 mt-1">
                      Confidence: {(reports[0].disease_analysis.parkinson.confidence * 100).toFixed(1)}%
                    </div>
                  </div>
                </div>
              </div>

              {/* Data Quality */}
              <div className="bg-slate-900/60 rounded-2xl border border-slate-800 p-6">
                <h3 className="text-lg font-semibold text-white mb-4">Data Quality Metrics</h3>
                <div className="space-y-4">
                  <div>
                    <div className="flex justify-between items-center mb-2">
                      <span className="text-sm font-medium text-slate-300">Data Completeness</span>
                      <span className="text-lg font-bold text-emerald-400">
                        {reports[0].quality.data_completeness.toFixed(1)}%
                      </span>
                    </div>
                    <div className="w-full bg-slate-800 rounded-full h-3">
                      <div
                        className="bg-gradient-to-r from-emerald-500 to-teal-500 h-3 rounded-full transition-all"
                        style={{ width: `${reports[0].quality.data_completeness}%` }}
                      />
                    </div>
                  </div>

                  <div>
                    <div className="flex justify-between items-center mb-2">
                      <span className="text-sm font-medium text-slate-300">Consistency Score</span>
                      <span className="text-lg font-bold text-blue-400">
                        {reports[0].cross_modal.consistency_score.toFixed(1)}%
                      </span>
                    </div>
                    <div className="w-full bg-slate-800 rounded-full h-3">
                      <div
                        className="bg-gradient-to-r from-blue-500 to-cyan-500 h-3 rounded-full transition-all"
                        style={{ width: `${reports[0].cross_modal.consistency_score}%` }}
                      />
                    </div>
                  </div>

                  <div className="flex items-center justify-between p-3 bg-slate-800/50 rounded-lg">
                    <span className="text-sm text-slate-300">Outliers Detected</span>
                    {reports[0].quality.has_outliers ? (
                      <ExclamationTriangleIcon className="h-5 w-5 text-amber-400" />
                    ) : (
                      <CheckCircleIcon className="h-5 w-5 text-emerald-400" />
                    )}
                  </div>

                  <div className="flex items-center justify-between p-3 bg-slate-800/50 rounded-lg">
                    <span className="text-sm text-slate-300">Conflicts</span>
                    {reports[0].cross_modal.has_conflicts ? (
                      <ExclamationTriangleIcon className="h-5 w-5 text-amber-400" />
                    ) : (
                      <CheckCircleIcon className="h-5 w-5 text-emerald-400" />
                    )}
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* Reports List */}
          <div>
            <h2 className="text-xl font-semibold text-white mb-4">
              All Reports ({reports.length})
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {reports.map((report) => (
                <div
                  key={report.id}
                  className="bg-slate-900/60 rounded-xl border border-slate-800 hover:border-purple-500/50 transition-all cursor-pointer border-l-4 border-l-purple-500 p-6 group"
                  onClick={() => setSelectedReport(report)}
                >
                  <div className="flex justify-between items-start mb-4">
                    <div>
                      <h3 className="text-lg font-semibold text-slate-100 group-hover:text-purple-300 transition-colors">
                        Report #{report.id}
                      </h3>
                      <p className="text-sm text-slate-400">
                        {new Date(report.generated_at).toLocaleDateString('en-US', {
                          year: 'numeric',
                          month: 'long',
                          day: 'numeric',
                          hour: '2-digit',
                          minute: '2-digit',
                        })}
                      </p>
                    </div>
                    <span
                      className={`px-3 py-1 rounded-full text-xs font-semibold border ${getInterpretationColor(
                        report.interpretation.overall
                      )}`}
                    >
                      {report.interpretation.overall.replace('_', ' ').toUpperCase()}
                    </span>
                  </div>

                  {/* Fusion Score */}
                  <div className="mb-4">
                    <div className="flex justify-between text-sm mb-1">
                      <span className="font-semibold text-slate-300">Integrated Fusion Score</span>
                      <span
                        className={`font-bold ${getConfidenceColor(report.fusion_scores.confidence)}`}
                      >
                        {report.fusion_scores.integrated.toFixed(1)}/100
                      </span>
                    </div>
                    <div className="w-full bg-slate-800 rounded-full h-2">
                      <div
                        className="bg-gradient-to-r from-purple-500 to-pink-500 h-2 rounded-full transition-all"
                        style={{ width: `${report.fusion_scores.integrated}%` }}
                      />
                    </div>
                  </div>

                  {/* Primary Concern */}
                  <div className="mb-4">
                    <p className="text-sm font-semibold text-slate-300">Primary Concern:</p>
                    <p className="text-sm text-slate-100">{report.interpretation.primary_concern}</p>
                  </div>

                  {/* Modality Scores */}
                  <div className="grid grid-cols-3 gap-2 text-xs">
                    <div className="bg-blue-900/30 p-2 rounded border border-blue-700/30">
                      <p className="text-slate-400">Cognitive</p>
                      <p className="font-semibold text-slate-100">
                        {report.fusion_scores.cognitive.toFixed(0)}
                      </p>
                    </div>
                    <div className="bg-emerald-900/30 p-2 rounded border border-emerald-700/30">
                      <p className="text-slate-400">Biomarker</p>
                      <p className="font-semibold text-slate-100">
                        {report.fusion_scores.biomarker.toFixed(0)}
                      </p>
                    </div>
                    <div className="bg-purple-900/30 p-2 rounded border border-purple-700/30">
                      <p className="text-slate-400">Imaging</p>
                      <p className="font-semibold text-slate-100">
                        {report.fusion_scores.imaging.toFixed(0)}
                      </p>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* Report Detail Modal */}
      {selectedReport && (
        <div className="fixed inset-0 bg-black/80 backdrop-blur-sm flex items-center justify-center z-50 p-4 overflow-y-auto">
          <div className="bg-slate-900 rounded-2xl border border-slate-800 max-w-4xl w-full max-h-[90vh] overflow-y-auto">
            {/* Modal Header */}
            <div className="sticky top-0 bg-gradient-to-r from-purple-900/90 to-pink-900/90 backdrop-blur-sm border-b border-slate-800 p-6 flex justify-between items-start z-10">
              <div>
                <h2 className="text-2xl font-bold text-white mb-1">
                  Fusion Report #{selectedReport.id}
                </h2>
                <p className="text-sm text-purple-200">
                  Patient ID: {selectedReport.patient_id} | Generated:{' '}
                  {new Date(selectedReport.generated_at).toLocaleString()}
                </p>
              </div>
              <div className="flex gap-2">
                <button
                  onClick={() => downloadReport(selectedReport)}
                  className="p-2 bg-slate-800 hover:bg-slate-700 text-white rounded-lg transition-all"
                  title="Download Report"
                >
                  <ArrowDownTrayIcon className="h-5 w-5" />
                </button>
                <button
                  onClick={() => setSelectedReport(null)}
                  className="p-2 bg-slate-800 hover:bg-slate-700 text-white rounded-lg transition-all"
                >
                  <XMarkIcon className="h-5 w-5" />
                </button>
              </div>
            </div>

            {/* Modal Content */}
            <div className="p-6 space-y-6">
              {/* Executive Summary */}
              <section className="bg-slate-800/50 rounded-xl p-6 border border-slate-700">
                <h3 className="text-lg font-semibold text-purple-300 mb-3 flex items-center gap-2">
                  <SparklesIcon className="h-5 w-5" />
                  Executive Summary
                </h3>
                <p className="text-slate-300 whitespace-pre-line leading-relaxed">
                  {selectedReport.report.executive_summary}
                </p>
              </section>

              {/* Detailed Findings */}
              <section className="bg-slate-800/50 rounded-xl p-6 border border-slate-700">
                <h3 className="text-lg font-semibold text-blue-300 mb-3">Detailed Findings</h3>
                <p className="text-slate-300 whitespace-pre-line leading-relaxed font-mono text-sm">
                  {selectedReport.report.detailed_findings}
                </p>
              </section>

              {/* Risk Assessment */}
              <section className="bg-slate-800/50 rounded-xl p-6 border border-slate-700">
                <h3 className="text-lg font-semibold text-amber-300 mb-3">Risk Assessment</h3>
                <p className="text-slate-300 whitespace-pre-line leading-relaxed font-mono text-sm">
                  {selectedReport.report.risk_assessment}
                </p>
              </section>

              {/* Recommendations */}
              <section className="bg-slate-800/50 rounded-xl p-6 border border-slate-700">
                <h3 className="text-lg font-semibold text-emerald-300 mb-3">Recommendations</h3>
                <p className="text-slate-300 whitespace-pre-line leading-relaxed">
                  {selectedReport.report.recommendations}
                </p>
              </section>

              {/* Follow-up Plan */}
              <section className="bg-slate-800/50 rounded-xl p-6 border border-slate-700">
                <h3 className="text-lg font-semibold text-pink-300 mb-3">Follow-up Plan</h3>
                <p className="text-slate-300 whitespace-pre-line leading-relaxed">
                  {selectedReport.report.follow_up_plan}
                </p>
              </section>

              {/* Footer */}
              <div className="text-center text-xs text-slate-500 pt-4 border-t border-slate-800">
                <p>Generated by NeuroPredict-AI Advanced Data Fusion System</p>
                <p className="text-purple-400 mt-1">
                  PATENT PENDING - Multi-Modal Integration Algorithm
                </p>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
